name: content_managment_app_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  image_picker: ^1.1.2
  uuid: ^4.5.1
  video_player: ^2.9.1
  web_socket_channel: ^3.0.1
  mobile_scanner: ^6.0.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
dependency_overrides: 
  

flutter:
  uses-material-design: true
  assets:
    - assets/sample.mp4
    - assets/sample.png